# Generated by Django 3.1.5 on 2021-02-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='signed_up_users',
            field=models.ManyToManyField(blank=True, to='profiles.UserProfile'),
        ),
    ]
