# Generated by Django 3.1.5 on 2021-01-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210125_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='friendly_name',
            field=models.CharField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='bgg_url',
            field=models.URLField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='designer',
            field=models.CharField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
