# Generated by Django 3.1.5 on 2021-02-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_product_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ManyToManyField(blank=True, related_name='product_category_id', to='games.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mechanic_id',
            field=models.ManyToManyField(blank=True, related_name='product_mechanic_id', to='games.Mechanic'),
        ),
    ]
