# Generated by Django 3.1.5 on 2021-02-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20210218_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_membership',
            field=models.BooleanField(default=False),
        ),
    ]
