# Generated by Django 3.1.5 on 2021-02-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_product_is_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_players',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_players',
            field=models.IntegerField(null=True),
        ),
    ]
