# Generated by Django 3.1.5 on 2021-02-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20210223_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='complexity',
        ),
    ]
